'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
type Account = { id: string; channel: string; displayName: string | null; externalAccountId: string; status: string; metadata: unknown };
export function IntegrationCards({ accounts, demo, canManage }: { accounts: Account[]; demo: boolean; canManage: boolean }) {
  const router = useRouter(); const [message, setMessage] = useState(''); const [text, setText] = useState('GUIA'); const [type, setType] = useState('COMMENT'); const [postId, setPost] = useState('demo-post'); const [busy, setBusy] = useState(false); const [conversationId, setConversation] = useState('');
  async function action(channel: string, action: string) {
    setBusy(true); setMessage('');
    try { const response = await fetch('/api/demo-channels', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ channel, action, text, type, postId }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); setMessage(action === 'event' ? `Evento simulado procesado: ${result.data.eventId}` : 'Conexión demo actualizada.'); setConversation(result.data.conversationId ?? ''); router.refresh(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Error.'); } finally { setBusy(false); }
  }
  return <><div className="space-y-2 lg:col-span-2"><h2 className="text-xl font-semibold">Canales sociales</h2><p className="text-sm text-slate-500">{demo ? 'Modo demo local · no usa APIs reales ni acredita App Review.' : 'Conexión productiva pendiente de habilitación y revisión.'}</p>{message && <p role="status" className="break-words text-sm">{message} {conversationId && <Link className="text-indigo-700" href={`/inbox/${conversationId}`}>Abrir Inbox →</Link>}</p>}</div>
    {['INSTAGRAM', 'MESSENGER', 'TIKTOK'].map(channel => { const account = accounts.find(a => a.channel === channel); const labels: Record<string, string> = { DISCONNECTED: 'NOT_CONNECTED', NEEDS_ATTENTION: 'ERROR' }; return <section key={channel} className="space-y-3 rounded-xl border bg-white p-5"><div className="flex justify-between"><h3 className="font-semibold">{channel}</h3><span className="text-xs">{account ? labels[account.status] ?? account.status : channel === 'TIKTOK' ? 'REVIEW_REQUIRED' : 'NOT_CONNECTED'}</span></div><p className="text-sm text-slate-500">{channel === 'INSTAGRAM' ? 'Instagram Login · cuenta profesional · no requiere Página Facebook.' : channel === 'MESSENGER' ? 'Facebook Login · Facebook Page · Page Access Token.' : 'Acceso de mensajería pendiente de aprobación.'}</p>{account && <p className="break-all text-xs">{account.displayName} · {account.externalAccountId}</p>}
      {demo && canManage ? <div className="flex flex-wrap gap-3"><button disabled={busy} className="rounded-lg border px-3 py-2 text-sm" onClick={() => action(channel, account?.status === 'CONNECTED' ? 'disconnect' : 'connect')}>{account?.status === 'CONNECTED' ? 'Desconectar demo' : 'Fake Connect'}</button>{account?.status === 'CONNECTED' && channel !== 'TIKTOK' && <button disabled={busy} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm text-white" onClick={() => action(channel, 'event')}>Disparar evento fake</button>}</div> : <p className="text-xs text-slate-500">Conectar {channel}: disponible después de completar validación local y acceso del proveedor.</p>}
    </section>; })}
    {demo && canManage && <section className="grid gap-3 rounded-xl border bg-indigo-50 p-5 lg:col-span-2 sm:grid-cols-3"><label className="text-sm">Evento<select aria-label="Evento" className="mt-1 w-full rounded border bg-white p-2" value={type} onChange={e => setType(e.target.value)}><option value="COMMENT">Comentario</option><option value="DM_RECEIVED">DM recibido</option><option value="STORY_REPLY">Respuesta Story</option></select></label><label className="text-sm">Texto<input className="mt-1 w-full rounded border bg-white p-2" value={text} onChange={e => setText(e.target.value)} /></label><label className="text-sm">ID post/reel<input className="mt-1 w-full rounded border bg-white p-2" value={postId} onChange={e => setPost(e.target.value)} /></label></section>}
  </>;
}
