'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
type Version = { id: string; version: number; status: string; instructions: string; allowedTools: string[]; options: unknown; maxSteps: number };
const defaultProfile: Record<string, string> = { role: 'Asistente del negocio', business: '', tone: 'Cercano y claro', language: 'Español', objective: 'Ayudar con información verificada del negocio', sales: 'Consultar catálogo. Confirmar producto y precio antes de crear checkout.', escalation: 'Derivar cuando el cliente lo pida o falte información.', forbidden: 'No inventar precios, políticas ni información de otros negocios.' };
export function AgentSettings({ agent, tools, canManage, canPublish, demo }: { agent: { id: string; name: string; isActive: boolean; versions: Version[] } | null; tools: string[]; canManage: boolean; canPublish: boolean; demo: boolean }) {
  const router = useRouter(); const [name, setName] = useState(agent?.name ?? 'Agente del negocio'); const [active, setActive] = useState(agent?.isActive ?? true);
  const [profile, setProfile] = useState({ ...defaultProfile, ...(agent?.versions[0]?.options as { profile?: Record<string, string> } | null)?.profile });
  const [allowedTools, setTools] = useState(agent?.versions[0]?.allowedTools ?? tools);
  const [selected, setSelected] = useState(agent?.versions[0]?.id ?? '');
  const [message, setMessage] = useState(''); const [question, setQuestion] = useState('¿Qué productos y servicios ofrecen?'); const [reply, setReply] = useState(''); const [calls, setCalls] = useState<unknown>([]); const [busy, setBusy] = useState(false);
  async function send(action: 'save' | 'test' | 'publish') {
    setBusy(true); setMessage('');
    try {
      const url = action === 'save' ? '/api/agent-settings' : `/api/agents/${agent?.id}/${action}`;
      const payload = action === 'save' ? { name, active, profile, allowedTools, maxSteps: 8 } : { versionId: selected, ...(action === 'test' ? { message: question } : {}) };
      const response = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.message);
      if (action === 'test') { setReply(result.data.reply ?? result.data.note ?? result.data.status); setCalls(result.data.toolCalls); }
      else { if (action === 'save') setSelected(result.data.versionId); setMessage(action === 'save' ? 'Nuevo borrador guardado. Selecciónalo para probar.' : 'Agente publicado.'); router.refresh(); }
    } catch (e) { setMessage(e instanceof Error ? e.message : 'Error.'); } finally { setBusy(false); }
  }
  const input = 'mt-1 w-full rounded-lg border bg-white p-3 text-sm';
  const labels: Record<string, string> = { role: 'Rol', business: 'Descripción del negocio', tone: 'Tono', language: 'Idioma', objective: 'Objetivo principal', sales: 'Instrucciones de venta', escalation: 'Escalamiento', forbidden: 'Comportamientos prohibidos' };
  return <div className="space-y-6"><div className="grid gap-4 lg:grid-cols-2"><section className="space-y-3 rounded-xl border bg-white p-5"><label className="block text-sm">Nombre<input className={input} disabled={!canManage} value={name} onChange={e => setName(e.target.value)} /></label><label className="text-sm"><input disabled={!canManage} type="checkbox" checked={active} onChange={e => setActive(e.target.checked)} /> Activo</label>{Object.keys(defaultProfile).map(key => <label key={key} className="block text-sm">{labels[key]}<textarea className={input} disabled={!canManage} rows={key === 'sales' || key === 'forbidden' ? 3 : 2} value={profile[key]} onChange={e => setProfile({ ...profile, [key]: e.target.value })} /></label>)}<details><summary className="text-sm">Herramientas autorizadas</summary><div className="mt-3 grid gap-2">{tools.map(t => <label key={t} className="text-xs"><input disabled={!canManage} type="checkbox" checked={allowedTools.includes(t)} onChange={e => setTools(e.target.checked ? [...allowedTools, t] : allowedTools.filter(v => v !== t))} /> {t}</label>)}</div></details><button disabled={busy || !canManage} onClick={() => send('save')} className="rounded-lg bg-indigo-600 px-4 py-2 text-white">Guardar nuevo Draft</button></section>
    <section className="space-y-4 rounded-xl border bg-white p-5"><h2 className="font-semibold">Probar agente</h2><p className="text-sm text-slate-500">{demo ? 'Proveedor fake local. Consulta datos reales del workspace de pruebas.' : 'Sandbox del agente.'} No envía mensajes sociales. Las herramientas con efectos se simulan.</p><label className="block text-sm">Versión a probar<select aria-label="Versión a probar" className={input} value={selected} onChange={e => setSelected(e.target.value)}><option value="">Seleccionar</option>{agent?.versions.map(v => <option key={v.id} value={v.id}>v{v.version} · {v.status}</option>)}</select></label><textarea aria-label="Mensaje de prueba" rows={3} className={input} value={question} onChange={e => setQuestion(e.target.value)} /><button disabled={busy || !selected || !canManage} onClick={() => send('test')} className="rounded-lg border px-4 py-2">Probar versión seleccionada</button>{reply && <div role="status" className="whitespace-pre-wrap break-words rounded-xl bg-indigo-50 p-4 text-sm">{reply}</div>}<details><summary className="text-sm">Panel técnico · tool calls</summary><pre className="overflow-auto text-xs">{JSON.stringify(calls, null, 2)}</pre></details><button disabled={busy || !selected || !canPublish} onClick={() => send('publish')} className="rounded-lg bg-indigo-600 px-4 py-2 text-white disabled:opacity-40">Publicar versión seleccionada</button><p className="text-xs text-slate-500">Publicar requiere rol owner. Las versiones publicadas no se editan.</p></section></div>{message && <p role="status">{message}</p>}</div>;
}
