import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { prisma } from '../../src/lib/prisma';
import { isLocalDemo } from '../../src/lib/testing/local-mode';
import { createCustomerWorkspace } from '../../src/lib/subscription';
import { ALL_TOOL_NAMES, toolByName } from '../../src/lib/agents/tools';
import { runAgent } from '../../src/lib/agents/runner';
import { ScriptedProvider, type ModelProvider, type ModelResponse } from '../../src/lib/agents/provider';
import { generateQuickFlow } from '../../src/lib/automations/catalog';
import { createFlow, saveFlow, validatePublication } from '../../src/lib/automations/service';
import { startFlowRun, advanceFlowRun } from '../../src/lib/automations/engine';
import { triggerMatchesEvent } from '../../src/lib/automations/triggers';
import { activateHumanControl } from '../../src/lib/whatsapp/human-control';
import { sendChannelMessage } from '../../src/lib/channels/outbound';
import type { FlowGraph } from '../../src/lib/automations/schema';
if (!isLocalDemo()) throw new Error('C2 requiere runtime visual protegido.');
let checks = 0;
function check(name: string, value: unknown) { assert.ok(value, name); checks++; console.log(`PASS ${name}`); }
const ids: string[] = [];
try {
  async function tenant(key: string) {
    const { workspace, user } = await createCustomerWorkspace({ companyName: `Smoke C2 ${key} ${randomUUID()}`, ownerName: 'Test', email: `${randomUUID()}@visual.test`, password: 'OnlyLocal#C2Tests!' }); ids.push(workspace.id);
    await prisma.workspaceActivation.upsert({ where: { workspaceId: workspace.id }, create: { workspaceId: workspace.id, status: 'ACTIVE' }, update: { status: 'ACTIVE' } });
    const account = await prisma.channelAccount.create({ data: { workspaceId: workspace.id, channel: 'INSTAGRAM', externalAccountId: randomUUID(), status: 'CONNECTED', metadata: { fake: true } } });
    const contact = await prisma.contact.create({ data: { workspaceId: workspace.id, firstName: key, lastName: 'C2' } });
    await prisma.contactChannelIdentity.create({ data: { workspaceId: workspace.id, contactId: contact.id, channel: 'INSTAGRAM', channelAccountId: account.id, externalUserId: randomUUID() } });
    const conversation = await prisma.conversation.create({ data: { workspaceId: workspace.id, contactId: contact.id, channelType: 'INSTAGRAM', channelAccountId: account.id, mode: 'AI_ACTIVE' } });
    const definition = await prisma.agentDefinition.findFirstOrThrow({ where: { workspaceId: workspace.id, key: 'SALES' } });
    const version = await prisma.agentVersion.findFirstOrThrow({ where: { agentDefinitionId: definition.id } });
    await prisma.agentVersion.update({ where: { id: version.id }, data: { status: 'PUBLISHED', allowedTools: ALL_TOOL_NAMES } });
    const product = await prisma.product.create({ data: { workspaceId: workspace.id, name: `Producto ${key}`, status: 'ACTIVE', variants: { create: { name: 'Digital', priceClp: key === 'A' ? 5900 : 9900, isDefault: true } } } });
    await prisma.knowledgeSource.create({ data: { workspaceId: workspace.id, type: 'FAQ', title: 'Horario', content: `Secreto de ${key}` } });
    return { workspaceId: workspace.id, user, account, contact, conversation, version, product };
  }
  const A = await tenant('A'), B = await tenant('B');
  const graph = generateQuickFlow({ kind: 'faq', accountId: A.account.id, agentVersionId: A.version.id });
  check('valid publication uses owned account and agent', (await validatePublication(A.workspaceId, 'INSTAGRAM', graph)).length === 0);
  const cross = structuredClone(graph); const ai = cross.nodes.find(n => n.type === 'AI')!; if (ai.type === 'AI') ai.agentVersionId = B.version.id;
  check('publish rejects AgentVersion B in A', (await validatePublication(A.workspaceId, 'INSTAGRAM', cross)).some(e => e.includes('agente')));
  const flow = await createFlow(A.workspaceId, A.user.id, 'AI wired', 'INSTAGRAM', graph);
  const version = await saveFlow(A.workspaceId, flow.id, A.user.id, { action: 'publish', versionId: flow.versions[0].id });
  await assert.rejects(() => saveFlow(A.workspaceId, flow.id, A.user.id, { action: 'save', versionId: version.id, graph }), /inmutable/); check('published graph immutable', true);
  const drafts = await Promise.all([1, 2].map(() => saveFlow(A.workspaceId, flow.id, A.user.id, { action: 'draft', versionId: version.id })));
  check('concurrent draft requests return one draft', drafts[0].id === drafts[1].id);
  const run = await startFlowRun({ workspaceId: A.workspaceId, flowId: flow.id, flowVersionId: version.id, contactId: A.contact.id, conversationId: A.conversation.id, channel: 'INSTAGRAM', provider: new ScriptedProvider([{ toolCalls: [{ id: 'kb', name: 'searchKnowledge', arguments: { query: '' } }] }, { text: 'Conocimiento consultado.' }]) });
  check('AI node starts actual runner', run.started);
  const agentRun = await prisma.agentRun.findFirstOrThrow({ where: { workspaceId: A.workspaceId, trigger: { startsWith: 'flow:' } } });
  check('AgentRun persisted with selected version', agentRun.agentVersionId === A.version.id && agentRun.status === 'COMPLETED');
  const state = await prisma.automationFlowRun.findUniqueOrThrow({ where: { id: run.started ? run.runId : '' } });
  check('run inspector has timeline', Array.isArray((state.state as { timeline?: unknown }).timeline));
  const badStart = await startFlowRun({ workspaceId: B.workspaceId, flowId: flow.id, flowVersionId: version.id }); check('cross-tenant FlowVersion rejected', !badStart.started);
  await assert.rejects(() => startFlowRun({ workspaceId: A.workspaceId, flowId: flow.id, flowVersionId: version.id, contactId: B.contact.id }), /workspace/); check('cross-tenant Contact rejected', true);
  const ctx = { workspaceId: A.workspaceId, contactId: A.contact.id, conversationId: A.conversation.id, agentRunId: agentRun.id };
  const knowledge = await toolByName('searchKnowledge')!.execute({ query: '' }, ctx);
  check('knowledge is isolated', JSON.stringify(knowledge).includes('Secreto de A') && !JSON.stringify(knowledge).includes('Secreto de B'));
  check('getProduct cannot load B', !(await toolByName('getProduct')!.execute({ productId: B.product.id }, ctx)).ok);
  check('checkout cannot load B', !(await toolByName('createCheckoutLink')!.execute({ productId: B.product.id }, ctx)).ok);
  check('checkout rejects model price/workspace input', !(await toolByName('createCheckoutLink')!.execute({ productId: A.product.id, workspaceId: B.workspaceId, price: 1 }, ctx)).ok);
  check('checkout requires customer confirmation', !(await toolByName('createCheckoutLink')!.execute({ productId: A.product.id }, ctx)).ok);
  const crossAgent = await runAgent({ workspaceId: A.workspaceId, conversationId: A.conversation.id, agentVersionId: B.version.id, dryRun: true, provider: new ScriptedProvider([{ text: 'not allowed' }]) }); check('runner rejects B version', crossAgent.status === 'ABORTED');
  const draft = await prisma.agentVersion.create({ data: { agentDefinitionId: A.version.agentDefinitionId, version: 2, instructions: 'Sandbox draft with isolated instructions.', model: 'fake', allowedTools: ['update_contact'] } });
  await runAgent({ workspaceId: A.workspaceId, conversationId: A.conversation.id, agentVersionId: draft.id, dryRun: true, provider: new ScriptedProvider([{ toolCalls: [{ id: 'x', name: 'update_contact', arguments: { firstName: 'MUTATED' } }] }, { text: 'Prueba.' }]) });
  check('sandbox draft remains DRAFT', (await prisma.agentVersion.findUniqueOrThrow({ where: { id: draft.id } })).status === 'DRAFT');
  check('sandbox does not execute material tools', (await prisma.contact.findUniqueOrThrow({ where: { id: A.contact.id } })).firstName === 'A');
  check('published agent remains published during draft test', (await prisma.agentVersion.findUniqueOrThrow({ where: { id: A.version.id } })).status === 'PUBLISHED');
  let release!: (value: ModelResponse) => void; let entered!: () => void;
  const enteredPromise = new Promise<void>(resolve => { entered = resolve; });
  const provider: ModelProvider = { name: 'deferred-fake', complete: async () => { entered(); return new Promise(resolve => { release = resolve; }); } };
  const pending = runAgent({ workspaceId: A.workspaceId, conversationId: A.conversation.id, provider }); await enteredPromise;
  await activateHumanControl({ workspaceId: A.workspaceId, conversationId: A.conversation.id });
  release({ text: 'Must never send', toolCalls: [], inputTokens: 0, outputTokens: 0 });
  check('pending AI invalidated by human takeover', (await pending).status === 'ABORTED');
  check('invalidated AI message absent', await prisma.message.count({ where: { conversationId: A.conversation.id, text: 'Must never send' } }) === 0);
  await sendChannelMessage({ workspaceId: A.workspaceId, conversationId: A.conversation.id, text: 'Respuesta humana', senderType: 'USER', origin: 'HUMAN', senderUserId: A.user.id });
  check('human composer uses social provider', await prisma.message.count({ where: { conversationId: A.conversation.id, senderType: 'USER', status: 'SENT' } }) === 1);
  await prisma.conversation.update({ where: { id: A.conversation.id }, data: { mode: 'AI_ACTIVE', lockVersion: { increment: 1 } } });
  check('return to AI allows next run', (await runAgent({ workspaceId: A.workspaceId, conversationId: A.conversation.id, provider: new ScriptedProvider([{ text: 'Nueva respuesta' }]) })).status === 'COMPLETED');
  const delay: FlowGraph = { trigger: { type: 'MESSAGE_RECEIVED', accountId: A.account.id }, nodes: [{ id: 'd1', type: 'DELAY', minutes: 1, respectQuietHours: false }, { id: 'd2', type: 'DELAY', minutes: 1, respectQuietHours: false }, { id: 'end', type: 'END' }], edges: [{ id: '1', from: 'd1', to: 'd2' }, { id: '2', from: 'd2', to: 'end' }] };
  const df = await createFlow(A.workspaceId, A.user.id, 'Delay restart', 'INSTAGRAM', delay); const dv = await saveFlow(A.workspaceId, df.id, A.user.id, { action: 'publish', versionId: df.versions[0].id });
  const dr = await startFlowRun({ workspaceId: A.workspaceId, flowId: df.id, flowVersionId: dv.id }); assert.ok(dr.started);
  await advanceFlowRun(dr.runId); check('cannot resume before deadline', (await prisma.automationFlowRun.findUniqueOrThrow({ where: { id: dr.runId } })).currentNodeId === 'd1');
  for (let i = 0; i < 2; i++) { await prisma.automationFlowRun.update({ where: { id: dr.runId }, data: { waitingUntil: new Date(0) } }); await advanceFlowRun(dr.runId); }
  check('two durable delays complete from persisted state', (await prisma.automationFlowRun.findUniqueOrThrow({ where: { id: dr.runId } })).status === 'COMPLETED');
  check('each delay enqueues a distinct resume job', await prisma.job.count({ where: { workspaceId: A.workspaceId, type: 'RUN_FLOW_STEP' } }) === 2);
  const evt = { eventId: 'e', workspaceId: A.workspaceId, channel: 'INSTAGRAM' as const, accountId: A.account.id, type: 'COMMENT', text: 'GUIA', postId: 'p', contactId: null, conversationId: null };
  check('specific post and exact keyword match', triggerMatchesEvent({ type: 'COMMENT', accountId: A.account.id, postId: 'p', keywords: ['GUIA'], match: 'EXACT' }, evt));
  check('wrong post blocked', !triggerMatchesEvent({ type: 'COMMENT', postId: 'other' }, evt));
  check('wrong account blocked', !triggerMatchesEvent({ type: 'COMMENT', accountId: B.account.id }, evt));
  check('exact keyword rejects substring', !triggerMatchesEvent({ type: 'COMMENT', keywords: ['GUIA'], match: 'EXACT' }, { ...evt, text: 'mi GUIA' }));
  check('FOLLOW publish blocked', (await validatePublication(A.workspaceId, 'INSTAGRAM', generateQuickFlow({ kind: 'follow', accountId: A.account.id }))).some(e => e.includes('FOLLOW_TRIGGER')));
  console.log(`C2 integration: ${checks}/${checks} PASS`);
} finally { await prisma.workspace.deleteMany({ where: { id: { in: ids } } }); await prisma.$disconnect(); }
